### ISSUE TITLE
new popup window with extra button

### ISSUE THREAD

**Issue by swasti2022** [DasJager/nightCafeCreditClaimer#5]
hello, 
first i want to say thank you for this script. i found and use it since some weeks.
today (maybe some more days ago) it dosnt work anymore.
it seems they have changed something. i have to click on an extra/new button in a new popup to claim.
can you fix this pleas? thank you!
regards

**Comment by NullShield-Official** [comment]
I do not see what you are referring to. When I naviagate to [THIS LINK](https://creator.nightcafe.studio/my-creations?claimTopup=true&n_class=topupReminder&n_medium=email) I do not see any extra popup window, photo  of the naviated link. Thank you very much for reaching out.  
![navigate](https://github.com/DasJager/nightCafeCreditClaimer/assets/61603670/4d9c46ec-06e9-4e9f-8842-6c17d583e9b3)

**Comment by swasti2022** [comment]
hello,

strange. today it worked. maybe some ff/tampermonkey issue after update.

thanks.

**Comment by NullShield-Official** [comment]
If you have any issues do not hesitate to let me know I will see if I can fix them.
